---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: debian-7.7
  - name: centos-7.0

suites:
  - name: default
    run_list:
      - recipe[setup_tests]
      - recipe[ceph_micro]
    attributes:
  - name: firefly
    run_list:
      - recipe[setup_tests]
      - recipe[ceph_micro]
    attributes:
      ceph_micro:
        version: 'firefly'
